"""Configuration (spec §11, ADR-022).

Resolution order: built-in defaults -> settings.json -> ATAMA_-prefixed env vars.
One schema drives config and the settings page; there is no file to keep in step with them.

**There is no `.env` any more** (user, 2026-09-12, ADR-022 amendment). The settings page is the
place you configure this app, including the API keys, and a second half-remembered file that
silently overrode it was a trap: a key set there could not be changed from the panel, and the
panel had to explain why. A `.env` left over from before is NOT read; `stale_dotenv()` finds it
and the launch says how to import it (`python -m backend.tools.migrate_env`). Nothing needs the
file at all: SEARXNG_SECRET, the one variable Docker Compose interpolates, is generated by the
launcher into the per-user state directory (`backend/tools/up.py`), so a fresh clone starts with
no file to create.

Secrets never leave the backend in full: use `hint()` for display.

Why the prefix on the last layer: our keys are named after what they configure (CLAUDE_MODEL,
CLAUDE_EFFORT...), and Claude Code exports variables of its own with those exact names — running
the app from inside a Claude Code session picked up CLAUDE_EFFORT=high from the parent shell
(found 2026-09-09). The process environment, which we do not own, is read only under `ATAMA_`.
"""
from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class Setting:
    key: str            # env-style name, e.g. WANIKANI_TOKEN; settings.json uses key.lower()
    default: Any
    type: type
    group: str
    description: str
    secret: bool = False
    #: A closed set of values (strings): the page shows a picker, `load()` and the panel refuse
    #: the rest. Empty = free text.
    choices: tuple[str, ...] = ()
    #: Inclusive bounds for a number. None = unbounded on that side.
    low: float | None = None
    high: float | None = None


class ConfigError(ValueError):
    """settings.json (or an ATAMA_* override) holds something this app cannot run with.

    One line, naming the key and the file, so a launch — or the pre-commit hook, which loads the
    config at import — prints what to fix instead of a traceback.
    """


# fmt: off
SCHEMA: tuple[Setting, ...] = (
    # Account & tokens
    Setting("WANIKANI_TOKEN", "", str, "account", "WaniKani personal access token (create with NO write permissions)", secret=True),
    Setting("BUNPRO_API_TOKEN", "", str, "account", "Bunpro -> Settings -> API -> Account API Token", secret=True),
    Setting("CLAUDE_CODE_OAUTH_TOKEN", "", str, "account", "Optional; from `claude setup-token`. Empty = interactive login", secret=True),
    # Model
    Setting("BRAIN_PROVIDER", "claude-cli", str, "model", "Which brain implementation to use (ADR-027). Implemented: claude-cli. An OpenAI headless provider is planned (ROADMAP subsystem 20)", choices=("claude-cli",)),
    Setting("CLAUDE_MODEL", "sonnet", str, "model", "Model tier for the tutor: sonnet | opus | haiku, each resolved to the NEWEST model your account can use (backend/data/model_tiers.txt, checked once a week). A full model id pins that exact model"),
    Setting("CLAUDE_EFFORT", "medium", str, "model", "CLI effort level (low|medium|high|xhigh|max). Measured 2026-09-09, median first-token BETWEEN turns / opening turn: low 2.75s/8.6s, medium 2.14s/5.8s, high 3.75s/19.2s. Medium is the floor, not a compromise: it is the fastest of the three on BOTH numbers, so dropping to low would buy nothing. Sonnet cannot turn thinking off at any level (docs, 2026-09-10); the Claude stage budget is 3.60s since ADR-033 (spec S10)", choices=("low", "medium", "high", "xhigh", "max")),
    Setting("CLAUDE_FALLBACK_MODEL", "haiku", str, "model", "Fallback when the model is overloaded / rate limited"),
    Setting("CLAUDE_REPLACE_SYSTEM_PROMPT", True, bool, "model", "true: --system-prompt (Sensei only). false: --append-system-prompt, which leaves Claude Code's coding-agent prompt in front and breaks the persona"),
    Setting("CLAUDE_TURN_TIMEOUT_S", 60, int, "model", "Per-turn timeout before SIGINT + apology", low=1),
    Setting("CLAUDE_CWD", "", str, "advanced", "Dir the claude subprocess runs in. Empty = platform default OUTSIDE the repo (Claude Code walks up the tree for CLAUDE.md and keys project memory by it — verified 2026-09-09)"),
    # Network
    Setting("HOST", "127.0.0.1", str, "advanced", "Bind address. Loopback only (ADR-017)"),
    Setting("PORT", 8000, int, "advanced", "Orchestrator port", low=1, high=65535),
    Setting("VOICEVOX_URL", "http://127.0.0.1:50021", str, "advanced", "VOICEVOX engine (local Docker)"),
    Setting("VOICEVOX_TIMEOUT_S", 30.0, float, "advanced", "How long one VOICEVOX request may take (s). Synthesis of a long sentence on a cold CPU engine can take a few seconds; 30 leaves room for a Docker engine that is still waking up without hanging the launch forever", low=1),
    Setting("SEARXNG_URL", "http://127.0.0.1:8888", str, "advanced", "Self-hosted SearxNG for the tutor's search tool (ADR-028). News also draws on the headline feeds in backend/data/news_feeds.txt"),
    # Voice
    Setting("VOICEVOX_SPEAKER", -1, int, "voice", "Base VOICEVOX style id. -1 = take it from the persona, which is what you usually want. 53 = 麒ヶ島宗麟 (たなか), 67 = 栗田まろん (はやし), 29 = No.7 (みなみ), 14 = 冥鳴ひまり (ゆい)"),
    Setting("VOICEVOX_SPEED_SCALE", 0.9, float, "voice", "Default speech speed for learners", low=0.5, high=2.0),
    Setting("VOICEVOX_INTONATION_SCALE", 1.0, float, "voice", "Default intonation. Above 1 is livelier, below 1 flatter", low=0.0, high=2.0),
    Setting("VOICEVOX_PITCH_SCALE", 0.0, float, "voice", "Baseline pitch shift for every emotion. Negative lowers the register: -0.06 to -0.12 makes a well-trained female voice read as male without losing its quality", low=-0.15, high=0.15),
    Setting("VOICEVOX_PRE_PHONEME", 0.0, float, "voice", "Lead-in silence per sentence (s). VOICEVOX defaults to 0.1, but we synthesise sentence by sentence, so it lands BETWEEN sentences as dead air", low=0.0, high=1.5),
    Setting("VOICEVOX_POST_PHONEME", 0.08, float, "voice", "Trailing silence per sentence (s). Enough to breathe, not enough to sound chopped", low=0.0, high=1.5),
    Setting("VOICEVOX_PAUSE_SCALE", 1.0, float, "voice", "Multiplies the pauses at 、 and 。 Higher is more measured", low=0.0, high=3.0),
    Setting("EMOTION_HAPPY", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_THINKING", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_SURPRISED", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_SERIOUS", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_ENCOURAGING", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_PROUD", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    Setting("EMOTION_CONFUSED", "", str, "voice", "Override for this emotion, e.g. style=31,speed=1.05,pitch=0.02,intonation=1.15. Empty = the built-in table in backend/emotions.py, which picks styles by name"),
    # Speech detection
    Setting("WHISPER_MODEL", "large-v3", str, "speech", "faster-whisper model (fallback: medium)"),
    Setting("WHISPER_COMPUTE_TYPE", "float16", str, "speech", "CTranslate2 compute type. float16 is the default because int8 buys nothing on a GPU that does fp16 natively: measured 2026-09-09, same median latency (287 vs 290 ms) and better transcripts, for 1.7 GB of headroom we were not spending. int8_float16 is the fallback if VRAM ever gets tight"),
    Setting("TURN_MODE", "ptt", str, "speech", "How a turn ends: ptt (you press a key - reliable, and the tutor's own voice can never end your turn) or vad (silence ends it - hands-free, but see VAD_SILENCE_MS)", choices=("ptt", "vad")),
    Setting("VAD_SILENCE_MS", 900, int, "speech", "Silence that ends an utterance. Raised 600 -> 900 on 2026-09-10: 600 ms cut the student off mid-thought. It is spent DIRECTLY from the 5.0 s voice->voice budget (spec S10 allots 0.50 s to this stage), so raising it buys patience with latency", low=0),
    Setting("VAD_MIN_SPEECH_MS", 300, int, "speech", "Minimum speech before an utterance counts", low=0),
    Setting("BARGEIN_THRESHOLD_FACTOR", 2.0, float, "speech", "VAD threshold multiplier while the avatar speaks", low=1.0),
    Setting("BARGEIN_MIN_SPEECH_MS", 250, int, "speech", "Sustained speech required to barge in", low=0),
    Setting("PLAYBACK_ONSET_IGNORE_MS", 150, int, "speech", "Ignore VAD at playback onset", low=0),
    # Speech detection, the knobs nobody should need (spec §11: still not magic numbers in code).
    Setting("VAD_SPEECH_THRESHOLD", 0.5, float, "advanced", "Silero probability at or above which a 32 ms frame counts as speech while listening. While the tutor speaks the bar is raised by BARGEIN_THRESHOLD_FACTOR (backend/vad.py active_threshold)", low=0.0, high=1.0),
    Setting("VAD_ONSET_TOLERANCE_MS", 200, int, "advanced", "How long a dip below the threshold may last before a forming utterance is abandoned. Speech is not continuous: plosives and syllable gaps dip constantly, and resetting on the first one meant speech was never detected (2026-09-09)", low=0),
    Setting("STT_QUIET_RMS", 0.012, float, "advanced", "Audio below this RMS is effectively silence, so a confident-sounding transcript on it is a lie (the hallucination filter). An upper bound: the voice loop measures the room between turns and uses a few times that level when it is lower (QUIET_OVER_FLOOR)", low=0.0, high=1.0),
    Setting("QUIET_OVER_FLOOR", 4.0, float, "advanced", "Audio this many times above the room's own level is not quiet. A fixed level assumed a loud microphone and, on a quiet headset (speech at rms 0.003), rejected real sentences as silence (2026-09-10)", low=1.0),
    Setting("STT_MIN_AVG_LOGPROB", -1.0, float, "advanced", "faster-whisper confidence floor: a transcript whose mean segment avg_logprob is below this is discarded (spec §9)", high=0.0),
    Setting("STT_MAX_NO_SPEECH_PROB", 0.6, float, "advanced", "Above this no_speech_prob the transcript is suspect - but never rejected on that alone: Whisper's no-speech head is unreliable on utterances that start abruptly, which is all of ours once Silero has trimmed the lead-in (2026-09-09). It needs quiet audio or STT_CORROBORATING_AVG_LOGPROB to agree", low=0.0, high=1.0),
    Setting("STT_CORROBORATING_AVG_LOGPROB", -0.7, float, "advanced", "The second opinion a high no_speech_prob needs: an avg_logprob below this corroborates it and the transcript is discarded", high=0.0),
    Setting("PTT_HANDOVER_TIMEOUT_S", 1.0, float, "advanced", "Releasing the talk key while the previous turn is still stopping: how long to wait for it before giving up on the new utterance (and saying so)", low=0.0, high=10.0),
    # Latency / VRAM guards. (No FILLER_AFTER_MS: the filler pool of spec §10 / ADR-008 is not built,
    # so the knob offered nothing - removed 2026-09-12.)
    Setting("LATENCY_WARN_S", 5.0, float, "advanced", "Warn when a turn exceeds this. 5.0 since 2026-09-10 (ADR-033): the gate is voice->voice p90 <= 5.0 s", low=0.0),
    Setting("VRAM_WARN_GB", 10, int, "advanced", "Warn above this GPU memory use", low=0),
    Setting("CONTEXT_ROTATE_AT", 0.7, float, "advanced", "Start a fresh session (with the lesson so far) when her context passes this fraction of the model's window, before Claude condenses it on its own - which is seconds of silence mid-lesson (ADR-032). 0 = never. The window is read from Claude after every turn. Where Claude condenses is its own policy and nothing reports it, so if Claude ever condenses first the app rotates earlier from then on (kept in .cache/compaction.json)", low=0.0, high=1.0),
    # Display
    Setting("TUTOR_PERSONA", "minami", str, "voice", "Which tutor: a name in prompts/ (tanaka, hayashi, minami, mori) or a path. The persona declares its own voice AND its avatar, so this one setting switches character, voice and face together (ADR-026/030). Default is minami because she is the one with a shipped avatar"),
    Setting("SUBTITLES", "jp", str, "display", "jp | off", choices=("jp", "off")),
    Setting("EXPLAIN_LANGUAGE", "en", str, "display", "Language for a grammar explanation when you click a red point: en | ja. A sentence translation is always English", choices=("en", "ja")),
    Setting("FURIGANA", "unknown", str, "display", "Furigana over kanji in the chat: all | unknown (only kanji you have not yet reached Guru on in WaniKani - the default) | off", choices=("all", "unknown", "off")),
    Setting("STUDY_PANEL", True, bool, "display", "The conversation as a chat beside the tutor: her grammar points in red, and a hint of what she wants you to use (ADR-036). Off = the tutor full-width, with subtitles"),
    Setting("AUDIO_INPUT_DEVICE", "", str, "audio", "Microphone, by name. Empty = system default. If it is unplugged, or not there at launch, the app uses the system default and switches back when it returns (spec §9)"),
    Setting("AUDIO_OUTPUT_DEVICE", "", str, "audio", "Speakers/headphones for the terminal voice (--speak), by name. Empty = system default. If they are unplugged, or not there at launch, the app uses the system default and switches back when they return (spec §9). On the avatar page her voice plays through the browser, which follows the OS default output"),
    Setting("STATUS_HEARTBEAT_S", 30, int, "display", "service_status heartbeat", low=1),
    # Files
    Setting("SETTINGS_FILE", "settings.json", str, "advanced", "Config store (git-ignored; mode 0600 where the OS has modes - Windows relies on the profile's ACLs)"),
    Setting("LOG_DIR", "logs", str, "advanced", "Session logs"),
    Setting("MEMORY_ENABLED", True, bool, "model", "Cross-session memory (spec §6b): the tutor remembers last session, avoids recently discussed topics, and keeps notes about you in an editable file outside the repo"),
    Setting("EXPLAIN_MODEL", "haiku", str, "model", "Model that answers a click on a grammar point or a translate icon (spec §8b). Cheap on purpose: it runs off the conversation path and every answer is cached"),
    Setting("MEMORY_SUMMARY_MODEL", "haiku", str, "model", "Model that summarises each past session at the next launch. Cheap on purpose: it runs once per session over a short excerpt, never on the conversation path"),
    Setting("CACHE_DIR", ".cache", str, "advanced", "Generated/personal files"),
    Setting("SRS_CACHE_TTL_S", 0, int, "advanced", "Launch re-uses an SRS snapshot younger than this many seconds instead of fetching. 0 (the default, user directive 2026-09-12): every launch fetches the latest WaniKani and Bunpro data; only a manual Refresh fetches after that (ADR-024)", low=0),
    Setting("SRS_FETCH_BUDGET_S", 10, int, "advanced", "Session-start fetch budget, PER SERVICE (they fetch in parallel). Measured 2026-09-09: bunpro 5.1s, wanikani 4.3s, so 10s is roughly 2x headroom. On timeout the last snapshot is served as stale, never dropped", low=1),
)
# fmt: on

KEYS: tuple[str, ...] = tuple(s.key for s in SCHEMA)
_BY_KEY = {s.key: s for s in SCHEMA}
SECRET_KEYS: frozenset[str] = frozenset(s.key for s in SCHEMA if s.secret)
#: String keys with a closed set of values, from the schema (the settings page reads this too).
CHOICES: dict[str, tuple[str, ...]] = {s.key: s.choices for s in SCHEMA if s.choices}


def _coerce(setting: Setting, raw: Any) -> Any:
    """The stored/env value as the schema's type — refusing what is outside its choices or range.

    Messages are `KEY: <problem>` so the settings panel can show the problem alone, per key.
    """
    if raw is None:
        return setting.default
    if setting.type is bool:
        return str(raw).lower() in ("1", "true", "yes", "on")
    try:
        value = setting.type(raw)
    except (TypeError, ValueError) as e:
        raise ConfigError(f"{setting.key}: expected {setting.type.__name__}, got {raw!r}") from e
    if setting.choices and value not in setting.choices:
        raise ConfigError(f"{setting.key}: one of: {', '.join(setting.choices)} (got {value!r})")
    if setting.type in (int, float):
        if setting.low is not None and value < setting.low:
            raise ConfigError(f"{setting.key}: must be at least {setting.low:g} (got {value!r})")
        if setting.high is not None and value > setting.high:
            raise ConfigError(f"{setting.key}: must be at most {setting.high:g} (got {value!r})")
    return value


class Config:
    """Resolved configuration. Attribute access by env-style key: cfg.WANIKANI_TOKEN."""

    def __init__(self, values: dict[str, Any], settings_path: Path, first_run: bool):
        self._values = values
        self.settings_path = settings_path
        self.first_run = first_run

    def __getattr__(self, key: str) -> Any:
        try:
            return self._values[key]
        except KeyError:
            raise AttributeError(key) from None

    def get(self, key: str) -> Any:
        return self._values[key]

    def secrets(self) -> dict[str, str]:
        """Secret values that are set. For handing to subprocess env blocks / redaction."""
        return {k: v for k, v in self._values.items() if k in SECRET_KEYS and v}

    def public_view(self) -> dict[str, Any]:
        """What the settings page / logs may see: secrets replaced by {set, hint}."""
        out: dict[str, Any] = {}
        for k, v in self._values.items():
            out[k] = {"set": bool(v), "hint": hint(v)} if k in SECRET_KEYS else v
        return out

    def path(self, key: str) -> Path:
        """Resolve a path-valued setting relative to the repo root."""
        return (REPO_ROOT / str(self._values[key])).resolve()


def claude_cwd(cfg: "Config") -> Path:
    """Working directory for the claude subprocess (spec §4). MUST be outside the repository:
    Claude Code discovers CLAUDE.md in ancestor directories and keys its project memory by the
    detected project root, so `.cache/claude-cwd` inside the repo was NOT isolated (init.memory_paths
    pointed at the Atama-AI project, 2026-09-09). Default: a per-user state dir; stable across
    restarts (session persistence is keyed by cwd, which --resume needs)."""
    configured = str(cfg.get("CLAUDE_CWD") or "").strip()
    if configured:
        p = Path(configured).expanduser()
        p = p if p.is_absolute() else (REPO_ROOT / p).resolve()
        if p == REPO_ROOT or REPO_ROOT in p.parents:
            import warnings
            warnings.warn(f"CLAUDE_CWD={configured!r} is inside the repository and would expose CLAUDE.md to the tutor; "
                          "using the platform default instead", RuntimeWarning, stacklevel=2)
        else:
            return p
    if os.name == "nt":
        # NOT %LOCALAPPDATA%: the Microsoft Store Python build virtualises writes under AppData
        # (MSIX), so a directory it creates there is invisible to cmd.exe/claude ("The current
        # directory is invalid.", 2026-09-09). The profile root is not virtualised.
        base = Path.home() / ".atama-ai"
    else:
        base = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local" / "state") / "atama-ai"
    return base / "claude-cwd"


def hint(value: str) -> str:
    return ("…" + value[-4:]) if value and len(value) >= 8 else ("set" if value else "")


def read_dotenv(path: Path) -> dict[str, str]:
    """Minimal .env parser: KEY=value lines, `#` comments, optional quotes. No expansion.

    Not part of configuration any more — it is how `migrate_env` imports an old file, and how the
    launch notices one still lying around (see the module docstring).
    """
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if value and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        else:
            value = value.split(" #", 1)[0].rstrip()
        if key:
            out[key] = value
    return out


ENV_PREFIX = "ATAMA_"


#: Keys that never moved into settings.json, so finding one in a `.env` is not a mistake:
#: SETTINGS_FILE says where settings.json IS (use ATAMA_SETTINGS_FILE to point elsewhere now).
DOTENV_BOOTSTRAP = frozenset({"SETTINGS_FILE"})


def stale_dotenv(path: Path | None = None) -> list[str]:
    """Keys of this app's schema still sitting in a `.env`, which nothing reads any more.

    Anything compose owns (SEARXNG_SECRET) is not ours, and the bootstrap keys above were never
    settings.json's to hold; neither is reported.
    """
    found = read_dotenv(REPO_ROOT / ".env" if path is None else path)
    return sorted(k for k in found if k in _BY_KEY and k not in DOTENV_BOOTSTRAP)


def env_overrides(environ: dict[str, str] | None = None) -> dict[str, str]:
    """Process-environment overrides, read ONLY under `ATAMA_` (see module docstring)."""
    environ = os.environ if environ is None else environ
    return {k[len(ENV_PREFIX):]: v for k, v in environ.items()
            if k.startswith(ENV_PREFIX) and k[len(ENV_PREFIX):] in _BY_KEY}


def load(settings_file: str | os.PathLike | None = None, env: dict[str, str] | None = None) -> Config:
    if env is None:
        # defaults < settings.json < ATAMA_* (the process environment is not our namespace).
        # A .env in the repo is deliberately NOT read: the settings page is the interface.
        env = env_overrides()
    settings_path = Path(settings_file or env.get("SETTINGS_FILE") or _BY_KEY["SETTINGS_FILE"].default)
    if not settings_path.is_absolute():
        settings_path = REPO_ROOT / settings_path
    stored: dict[str, Any] = {}
    first_run = not settings_path.exists()
    if not first_run:
        stored = _read_store(settings_path)
    values: dict[str, Any] = {}
    for s in SCHEMA:
        raw: Any = s.default
        where = "built-in default"
        if s.key.lower() in stored:
            raw, where = stored[s.key.lower()], str(settings_path)
        if s.key in env and env[s.key] != "":
            raw, where = env[s.key], f"{ENV_PREFIX}{s.key} in the environment"
        try:
            values[s.key] = _coerce(s, raw)
        except ConfigError as exc:
            raise ConfigError(f"{exc} — from {where}; fix it on the settings page or in that file") from None
    return Config(values, settings_path, first_run)


def _read_store(path: Path) -> dict[str, Any]:
    """settings.json as a dict, or one clear line about why it is not one."""
    try:
        data = json.loads(path.read_text(encoding="utf-8") or "{}")
    except (OSError, ValueError) as exc:
        raise ConfigError(f"{path} is not valid JSON ({exc}); fix or delete it") from None
    if not isinstance(data, dict):
        raise ConfigError(f"{path} must hold a JSON object, not {type(data).__name__}; fix or delete it")
    return data


def save(updates: dict[str, Any], settings_file: str | os.PathLike | None = None) -> Path:
    """Merge `updates` (env-style keys) into settings.json atomically.

    Written through a temp file + rename, mode 0600 where the OS supports modes; on Windows the
    profile directory's ACLs are the protection, and `chmod` is a no-op there.
    """
    cfg = load(settings_file)
    path = cfg.settings_path
    current: dict[str, Any] = {}
    if path.exists():
        current = _read_store(path)
    for key, value in updates.items():
        if key not in _BY_KEY:
            raise KeyError(f"unknown setting {key}")
        current[key.lower()] = _coerce(_BY_KEY[key], value)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".settings-", suffix=".json", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(current, f, indent=2, ensure_ascii=False)
        try:
            os.chmod(tmp, 0o600)
        except OSError:
            pass  # Windows: ACLs, not modes
        os.replace(tmp, path)
    except Exception:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise
    return path
