"""Generate frontend/src/protocol.gen.ts from backend/models.py (spec §8, ROADMAP 7, gate M3a).

The protocol is defined ONCE, in models.py. The page's types are generated from it rather than
mirrored by hand, so the two cannot drift: test_models.py re-renders this file and fails when the
committed copy differs, and the page's dispatcher (frontend/src/ws.ts `Handlers`) is typed so that
`tsc` fails while any server message type has no handler.

    .venv/Scripts/python -m backend.tools.gen_protocol           # rewrite the file
    .venv/Scripts/python -m backend.tools.gen_protocol --check   # exit 1 if it is stale
"""
from __future__ import annotations

import json
import sys
import types
from typing import Any, Literal, Union, get_args, get_origin

from backend import config, models

OUT = config.REPO_ROOT / "frontend" / "src" / "protocol.gen.ts"

HEADER = """\
// GENERATED by backend/tools/gen_protocol.py from backend/models.py - do not edit by hand.
// backend/tests/test_models.py fails while this file is out of date. After changing a message:
//   .venv/Scripts/python -m backend.tools.gen_protocol
"""


def _members(union) -> tuple[type, ...]:
    """The models of `Annotated[Union[...], Field(discriminator=...)]`, in declaration order."""
    return get_args(get_args(union)[0])


def ts(tp: Any) -> str:
    """A pydantic field annotation as a TypeScript type."""
    origin = get_origin(tp)
    if tp is Any:
        return "unknown"
    if tp is str:
        return "string"
    if tp in (int, float):
        return "number"
    if tp is bool:
        return "boolean"
    if tp is type(None):
        return "null"
    if origin is Literal:
        return " | ".join(json.dumps(a) for a in get_args(tp))
    if origin in (Union, types.UnionType):
        return " | ".join(ts(a) for a in get_args(tp))
    if origin is list:
        inner = ts(get_args(tp)[0])
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if origin is dict:
        key, value = get_args(tp)
        return f"Record<{ts(key)}, {ts(value)}>"
    raise TypeError(f"no TypeScript mapping for {tp!r} - extend gen_protocol.ts()")


def _doc(model: type) -> str:
    first = (model.__doc__ or "").strip().split("\n\n")[0]
    return " ".join(first.split())


def _interface(model: type, server: bool) -> str:
    """One message. A server message always carries every field (model_dump() writes them all);
    a client message may leave out any field that has a default."""
    lines = []
    doc = _doc(model)
    if doc:
        lines.append(f"/** {doc} */")
    lines.append(f"export interface {model.__name__}Msg {{")
    for name, field in model.model_fields.items():
        optional = "" if server or field.is_required() or name == "type" else "?"
        lines.append(f"  {name}{optional}: {ts(field.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def _const(name: str, values) -> str:
    return f"export const {name} = [{', '.join(json.dumps(v) for v in values)}] as const;"


def render() -> str:
    client, server = _members(models.ClientMessage), _members(models.ServerMessage)
    kind = lambda m: m.model_fields["type"].default  # noqa: E731
    parts = [
        HEADER,
        _const("CLIENT_TYPES", [kind(m) for m in client]),
        _const("SERVER_TYPES", [kind(m) for m in server]),
        _const("RESERVED_TYPES", sorted(models.RESERVED_TYPES)),
        "export type ClientType = (typeof CLIENT_TYPES)[number];",
        "export type ServerType = (typeof SERVER_TYPES)[number];",
        "",
        "// ------------------------------------------------------------------ client -> server",
        *(_interface(m, server=False) + "\n" for m in client),
        "// ------------------------------------------------------------------ server -> client",
        *(_interface(m, server=True) + "\n" for m in server),
        "export type ClientMessage = " + " | ".join(f"{m.__name__}Msg" for m in client) + ";",
        "export type ServerMessage = " + " | ".join(f"{m.__name__}Msg" for m in server) + ";",
        "",
    ]
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    text = render()
    current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
    if "--check" in argv:
        if current != text:
            print(f"{OUT} is out of date: run python -m backend.tools.gen_protocol", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(config.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
