// GENERATED by backend/tools/gen_protocol.py from backend/models.py - do not edit by hand.
// backend/tests/test_models.py fails while this file is out of date. After changing a message:
//   .venv/Scripts/python -m backend.tools.gen_protocol

export const CLIENT_TYPES = ["audio_chunk", "control", "settings", "settings_test"] as const;
export const SERVER_TYPES = ["state", "stt_partial", "stt_final", "assistant_text", "speak", "emotion", "bargein", "srs_profile", "service_status", "settings", "mic_level", "meters", "timing", "error"] as const;
export const RESERVED_TYPES = ["stt_partial"] as const;
export type ClientType = (typeof CLIENT_TYPES)[number];
export type ServerType = (typeof SERVER_TYPES)[number];

// ------------------------------------------------------------------ shared parts
/** Furigana for one run of kanji (spec §8b): characters [start, end) of the text, in code points, and its reading in hiragana. `known`: the student has passed every kanji in it on WaniKani — the page hides those by default (FURIGANA=unknown). */
export interface Reading {
  start: number;
  end: number;
  reading: string;
  known: boolean;
}

/** Where she used a grammar point in a `speak` sentence (ADR-036): characters [start, end) of `text`, counted in Unicode code points — the page counts the same way (Array.from). */
export interface GrammarSpan {
  start: number;
  end: number;
  point: string;
}

// ------------------------------------------------------------------ client -> server
/** Raw mic audio. PCM16 mono at 16 kHz (spec §9) — never encoded audio. */
export interface AudioChunkMsg {
  type: "audio_chunk";
  pcm16_b64: string;
  seq?: number;
}

/** Turn-taking and session control. */
export interface ControlMsg {
  type: "control";
  action: "start" | "stop" | "bargein_ack" | "resync" | "quit" | "new_topic" | "ready";
}

/** Partial update of any key in the `config.py` schema, secrets included (§11). */
export interface SettingsUpdateMsg {
  type: "settings";
  values: Record<string, unknown>;
}

/** Run one service's real check and report the result through `service_status` (§5b). */
export interface SettingsTestMsg {
  type: "settings_test";
  service: "wanikani" | "bunpro" | "bunpro_mcp" | "brain" | "search" | "voicevox" | "stt";
}

// ------------------------------------------------------------------ server -> client
export interface StateMsg {
  type: "state";
  state: "listening" | "thinking" | "speaking";
  turn: number;
}

/** RESERVED and never emitted in M2-M5. */
export interface SttPartialMsg {
  type: "stt_partial";
  text: string;
}

export interface SttFinalMsg {
  type: "stt_final";
  text: string;
  accepted: boolean;
  reason: string;
  readings: Reading[];
}

/** One sentence of the tutor's reply, for the subtitle strip. Emotion tags are already stripped by the chunker — a tag must never reach the display or the TTS (ADR-020). */
export interface AssistantTextMsg {
  type: "assistant_text";
  text: string;
}

/** One sentence of synthesised audio with its lip-sync timeline. */
export interface SpeakMsg {
  type: "speak";
  audio_b64: string;
  visemes: string[];
  vtimes: number[];
  vdurations: number[];
  text: string;
  emotion: string;
  turn: number;
  grammar: GrammarSpan[];
  target: string;
  used: string;
  readings: Reading[];
}

/** A mood change not tied to a spoken sentence — the idle face between turns. */
export interface EmotionMsg {
  type: "emotion";
  emotion: string;
}

/** The server has accepted an interruption: stop playback and drop queued audio of `turn` and every epoch before it. */
export interface BargeInMsg {
  type: "bargein";
  turn: number;
}

/** The rendered student profile, for the collapsible debug panel (§5). */
export interface SrsProfileMsg {
  type: "srs_profile";
  text: string;
}

/** One chip in the status bar (§5b). `last_error` is already sanitised by the registry — never a token, never a URL containing one. */
export interface ServiceStatusMsg {
  type: "service_status";
  service: string;
  state: string;
  detail: string;
  last_error: string;
}

/** Echo of the applied settings. Secrets appear ONLY as `{set: true, hint: "…abcd"}`; the stored value never returns to the browser (ADR-022). */
export interface SettingsMsg {
  type: "settings";
  values: Record<string, unknown>;
  fields: Record<string, unknown>[];
  pinned: Record<string, string>;
  saved: string[];
  errors: Record<string, string>;
}

/** Microphone level for the settings panel's meter — at most ~10 a second (spec §9). `level` is RMS (peak-held between sends); `speech` is the VAD's probability. */
export interface MicLevelMsg {
  type: "mic_level";
  level: number;
  speech: number;
}

/** The status bar's gauges (user request, 2026-09-10). Every field is optional: each arrives when its source reports — context and use after a turn, GPU memory on the heartbeat — and the server merges them, so a page always receives the latest of each. */
export interface MetersMsg {
  type: "meters";
  context_tokens: number | null;
  context_window: number | null;
  month_turns: number | null;
  limit_status: string | null;
  limit_type: string | null;
  limit_resets_at: number | null;
  vram_used_mib: number | null;
  vram_total_mib: number | null;
}

/** Per-turn stage breakdown (§10), so p50/p90 are measurable rather than anecdotal. */
export interface TimingMsg {
  type: "timing";
  stt_ms: number;
  first_chunk_ms: number;
  first_audio_ms: number;
  total_ms: number;
  barged_in: boolean;
  ttft_ms: number | null;
  thinking_chars: number;
  p50_ms: number | null;
  p90_ms: number | null;
  turns: number;
}

/** A problem the user should see. An unknown client message produces one of these rather than an exception — a malformed frame must not take the socket down. */
export interface ErrorMsg {
  type: "error";
  message: string;
  fatal: boolean;
}

export type ClientMessage = AudioChunkMsg | ControlMsg | SettingsUpdateMsg | SettingsTestMsg;
export type ServerMessage = StateMsg | SttPartialMsg | SttFinalMsg | AssistantTextMsg | SpeakMsg | EmotionMsg | BargeInMsg | SrsProfileMsg | ServiceStatusMsg | SettingsMsg | MicLevelMsg | MetersMsg | TimingMsg | ErrorMsg;
