// GENERATED by backend/tools/gen_protocol.py from backend/models.py - do not edit by hand.
// backend/tests/test_models.py fails while this file is out of date. After changing a message:
//   .venv/Scripts/python -m backend.tools.gen_protocol

export const CLIENT_TYPES = ["control", "settings", "explain"] as const;
export const SERVER_TYPES = ["state", "stt_partial", "stt_final", "speak", "bargein", "service_status", "settings", "mic_level", "meters", "timing", "explanation", "error"] as const;
export const RESERVED_TYPES = ["stt_partial"] as const;
export type ClientType = (typeof CLIENT_TYPES)[number];
export type ServerType = (typeof SERVER_TYPES)[number];

// ------------------------------------------------------------------ shared parts
/** Furigana for one run of kanji (spec §8b): characters [start, end) of the text, in code points, and its reading in hiragana. `known`: the student has passed every kanji in it on WaniKani — the page hides those by default (FURIGANA=unknown). */
export interface Reading {
  start: number;
  end: number;
  reading: string;
  known: boolean;
}

/** Where a word the student is still learning appears in a sentence (spec §8b, user 2026-09-12): characters [start, end) in code points, blue on the page. From the WaniKani snapshot already on disk (backend/study.py) — no model call, no fetch. */
export interface VocabSpan {
  start: number;
  end: number;
  word: string;
  reading: string;
  meaning: string;
  stage: string;
}

/** Where she used a grammar point in a `speak` sentence (ADR-036): characters [start, end) of `text`, counted in Unicode code points — the page counts the same way (Array.from). */
export interface GrammarSpan {
  start: number;
  end: number;
  point: string;
}

// ------------------------------------------------------------------ client -> server
/** Turn-taking and session control. */
export interface ControlMsg {
  type: "control";
  action: "start" | "stop" | "cancel" | "resync" | "quit" | "new_topic" | "ready";
}

/** Partial update of any key in the `config.py` schema, secrets included (§11). */
export interface SettingsUpdateMsg {
  type: "settings";
  values: Record<string, unknown>;
}

/** The student clicked something and wants it explained (spec §8b, ADR-036): a red grammar point, or a sentence's translate icon. Nothing is generated until this arrives. */
export interface ExplainMsg {
  type: "explain";
  kind: "grammar" | "sentence";
  text: string;
  context?: string;
  lang?: "en" | "ja";
}

// ------------------------------------------------------------------ server -> client
export interface StateMsg {
  type: "state";
  state: "listening" | "thinking" | "speaking";
  turn: number;
}

/** RESERVED and never emitted in M2-M5. */
export interface SttPartialMsg {
  type: "stt_partial";
  text: string;
}

export interface SttFinalMsg {
  type: "stt_final";
  text: string;
  accepted: boolean;
  reason: string;
  readings: Reading[];
  vocab: VocabSpan[];
}

/** One sentence of synthesised audio with its lip-sync timeline. */
export interface SpeakMsg {
  type: "speak";
  audio_b64: string;
  visemes: string[];
  vtimes: number[];
  vdurations: number[];
  text: string;
  emotion: string;
  turn: number;
  grammar: GrammarSpan[];
  target: string;
  used: string;
  used_kind: string;
  readings: Reading[];
  vocab: VocabSpan[];
}

/** The server has accepted an interruption: stop playback and drop queued audio of `turn` and every epoch before it. */
export interface BargeInMsg {
  type: "bargein";
  turn: number;
}

/** One chip in the status bar (§5b). `last_error` is already sanitised by the registry — never a token, never a URL containing one. */
export interface ServiceStatusMsg {
  type: "service_status";
  service: string;
  state: string;
  detail: string;
  last_error: string;
}

/** Echo of the applied settings. Secrets appear ONLY as `{set: true, hint: "…abcd"}`; the stored value never returns to the browser (ADR-022). */
export interface SettingsMsg {
  type: "settings";
  values: Record<string, unknown>;
  fields: Record<string, unknown>[];
  pinned: Record<string, string>;
  saved: string[];
  errors: Record<string, string>;
}

/** Microphone level for the settings panel's meter — at most ~10 a second (spec §9). `level` is RMS (peak-held between sends); `speech` is the VAD's probability. */
export interface MicLevelMsg {
  type: "mic_level";
  level: number;
  speech: number;
}

/** The status bar's gauges (user request, 2026-09-10). Every field is optional: each arrives when its source reports — context and use after a turn, GPU memory on the heartbeat — and the server merges them, so a page always receives the latest of each. */
export interface MetersMsg {
  type: "meters";
  context_tokens: number | null;
  context_window: number | null;
  month_turns: number | null;
  limit_status: string | null;
  limit_type: string | null;
  limit_resets_at: number | null;
  vram_used_mib: number | null;
  vram_total_mib: number | null;
}

/** Per-turn stage breakdown (§10), so p50/p90 are measurable rather than anecdotal. */
export interface TimingMsg {
  type: "timing";
  stt_ms: number;
  first_chunk_ms: number;
  first_audio_ms: number;
  first_play_ms: number;
  total_ms: number;
  barged_in: boolean;
  ttft_ms: number | null;
  thinking_chars: number;
  p50_ms: number | null;
  p90_ms: number | null;
  turns: number;
}

/** The answer to one `explain`, or why there is none. Cached on the orchestrator, so asking the same thing twice costs nothing. */
export interface ExplanationMsg {
  type: "explanation";
  kind: "grammar" | "sentence";
  text: string;
  answer: string;
  error: string;
}

/** A problem the user should see. An unknown client message produces one of these rather than an exception — a malformed frame must not take the socket down. */
export interface ErrorMsg {
  type: "error";
  message: string;
  fatal: boolean;
}

export type ClientMessage = ControlMsg | SettingsUpdateMsg | ExplainMsg;
export type ServerMessage = StateMsg | SttPartialMsg | SttFinalMsg | SpeakMsg | BargeInMsg | ServiceStatusMsg | SettingsMsg | MicLevelMsg | MetersMsg | TimingMsg | ExplanationMsg | ErrorMsg;
